
exports.config = 
{

    // router definitions
    'handlers' : {
        '/' : function ( req, res ) {
            this.log( " in Request Handler: 'root'" );
            this.serve_static( 'index.html', res );
        },

        '/generated_page' : function ( req, res ) {
            res.writeHead( 200, { 'Content-Type' : 'text/html' } );
            res.write( "<html><body><h2>Test Page</h2><br>Sample Page generated by router function</body></html>" );
            res.end();
        },

        '/show_config' : function( req, res ) {
            res.writeHead( 200, { 'Content-Type' : 'text/plain' } );
            res.write( this.pobj( this.default_config ) );
            res.end();
        }
    }
};
