
exports.config = 
{

    // router definitions
    'handlers' : {
        '/' : function ( req, res ) {
            lib.log( " in Request Handler: 'root'" );
            lib.serve_static( 'index.html', res );
        },
        '/test_page' : function ( req, res ) {
            res.writeHead( 200, { 'Content-Type' : 'text/html' } );
            res.write( "<html><body><h2>Test Page</h2><br>Sample Page generated by router function</body></html>" );
            res.end();
        },

        '/config' : function( req, res ) {
            
        }
    }
};
