
exports.config = 
{
    // optional but recommended. In fact all config options are optional.
    'application_name' : 'Simple Page',

    // router definitions
    'handlers' : {
        '/' : function ( req, res, lib ) {
            lib.log( " in Request Handler: 'root'" );
            lib.serve_static( 'index.html', res );
        },

        // note: lib is passed to handlers as additional third argument. It contains the 'get', 
        //        logging and other utility functions. But it doesn't have to be included, as in here -v
        '/generated_page' : function ( req, res ) {
            res.writeHead( 200, { 'Content-Type' : 'text/html' } );
            res.write( "<html><body><h2>Test Page</h2><br>Sample Page generated by router function</body></html>" );
            res.end();
        },

        '/analyze_get' : function( req, res, lib ) {
            var get = lib.config.get;
            res.writeHead( 200, { 'Content-Type' : 'text/html' } );
            res.write( '<html><body><h2>Analyze the get</h2><a href="/analyze_get/?q=roses+are+red&a=violets&b=are&c=blue">Try this one</a>' ); 
            if ( get && lib.type_of(get) === 'object' ) {
                var j = JSON.stringify( get, null, '  ' );
                res.write( '<pre>'+j+'</pre></body></html>' );
            } else {
                res.write( '</body></html>' );
            }
            res.end();
        },

        '/show_config' : function( req, res, lib ) {
            res.writeHead( 200, { 'Content-Type' : 'text/plain' } );
            res.write( lib.pobj( lib.config ) );
            res.end();
        }
    }
};
